name: "HomeRecall"
version: "1.0.35"
slug: "homerecall"
description: "A complete rewrite of TasmoBackup using .NET 10, supporting Tasmota, WLED, and Shelly."
url: "https://github.com/dasdandre/HomeRecall"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: services
boot: auto
init: false
map:
  - config:rw
  - share:rw
  - backup:rw
options:
  log_level: info
schema:
  log_level: "list(trace|debug|info|notice|warning|error|fatal)?"
ingress: true
ingress_port: 8080
panel_icon: mdi:cloud-upload
